declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    EXPO_PUBLIC_SUPABASE_REDIRECT_TO?: string;
    EXPO_PUBLIC_PASSWORD_RESET_REDIRECT_TO?: string;
    EXPO_PUBLIC_DELETE_ACCOUNT_FUNCTION_NAME?: string;
    EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
  }
}
